# Generated by Django 5.2.16 on 2026-07-29 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StoreSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_name', models.CharField(default='DESI VIBES', max_length=120)),
                ('tagline', models.CharField(blank=True, default='Modern Ethnic Wear for Men', max_length=200)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='brand/')),
                ('theme_color', models.CharField(default='#801C2A', max_length=20)),
                ('currency', models.CharField(default='INR', max_length=8)),
                ('gst_enabled', models.BooleanField(default=False)),
                ('gstin', models.CharField(blank=True, max_length=20)),
                ('default_gst_rate', models.DecimalField(decimal_places=2, default=5, max_digits=5)),
                ('default_hsn', models.CharField(blank=True, max_length=20)),
                ('cod_enabled', models.BooleanField(default=True)),
                ('prepaid_enabled', models.BooleanField(default=False)),
                ('crm_provider', models.CharField(choices=[('none', 'None / Excel'), ('zoho', 'Zoho CRM')], default='none', max_length=20)),
                ('shiprocket_enabled', models.BooleanField(default=False)),
                ('free_shipping_over', models.DecimalField(decimal_places=2, default=2999, max_digits=10)),
                ('flat_shipping_rate', models.DecimalField(decimal_places=2, default=99, max_digits=10)),
                ('support_email', models.EmailField(default='hello@desivibes.demo', max_length=254)),
                ('support_phone', models.CharField(default='+91 98765 43210', max_length=20)),
            ],
            options={
                'verbose_name': 'Store settings',
                'verbose_name_plural': 'Store settings',
            },
        ),
    ]
