# Generated by Django 5.2.16 on 2026-07-29 21:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_category_meta_description_category_meta_title_and_more'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeroSlide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=120)),
                ('subtitle', models.CharField(blank=True, max_length=255)),
                ('image', models.ImageField(upload_to='hero/')),
                ('mobile_image', models.ImageField(blank=True, null=True, upload_to='hero/')),
                ('cta_label', models.CharField(blank=True, default='Shop Collection', max_length=60)),
                ('cta_url', models.CharField(blank=True, default='/shop/', max_length=200)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.AddField(
            model_name='storesettings',
            name='about_body',
            field=models.TextField(blank=True, default='DESI VIBES was born from a love of Indian craft and modern silhouette. We design ethnic wear for men who want tradition with a contemporary edge—sharper cuts, richer fabrics, and colours that feel royal without the noise.'),
        ),
        migrations.AddField(
            model_name='storesettings',
            name='about_image',
            field=models.ImageField(blank=True, null=True, upload_to='brand/'),
        ),
        migrations.AddField(
            model_name='storesettings',
            name='about_title',
            field=models.CharField(blank=True, default='Our Story', max_length=120),
        ),
        migrations.AddField(
            model_name='storesettings',
            name='craft_body',
            field=models.TextField(blank=True, default='Every piece is cut and finished in India by skilled artisans. From Banarasi-inspired weaves to contemporary bandhgalas, our ateliers in Rajasthan and Uttar Pradesh bring heritage techniques into wearable luxury.'),
        ),
        migrations.AddField(
            model_name='storesettings',
            name='craft_image',
            field=models.ImageField(blank=True, null=True, upload_to='brand/'),
        ),
        migrations.AddField(
            model_name='storesettings',
            name='craft_locations',
            field=models.CharField(blank=True, default='Jaipur · Varanasi · New Delhi', help_text='Short line shown under craftsmanship section', max_length=255),
        ),
        migrations.AddField(
            model_name='storesettings',
            name='craft_title',
            field=models.CharField(blank=True, default='Crafted in India', max_length=120),
        ),
        migrations.AddField(
            model_name='storesettings',
            name='default_size_chart',
            field=models.TextField(blank=True, default='Size | Chest (in) | Waist (in) | Shoulder (in) | Length (in)\nXS | 36 | 30 | 15.5 | 38\nS | 38 | 32 | 16.5 | 40\nM | 40 | 34 | 17.5 | 42\nL | 42 | 36 | 18.5 | 44\nXL | 44 | 38 | 19.5 | 46\nXXL | 46 | 40 | 20.5 | 48\n\nTip: If you are between sizes, choose the larger size for a relaxed festive fit.'),
        ),
        migrations.AddField(
            model_name='storesettings',
            name='meta_description',
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AddField(
            model_name='storesettings',
            name='meta_title',
            field=models.CharField(blank=True, max_length=70),
        ),
        migrations.AddField(
            model_name='storesettings',
            name='seo_keywords',
            field=models.CharField(blank=True, default='ethnic wear, sherwani, kurta, bandhgala, nehru jacket, mens ethnic', max_length=255),
        ),
        migrations.CreateModel(
            name='CustomerReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=120)),
                ('location', models.CharField(blank=True, max_length=120)),
                ('rating', models.PositiveSmallIntegerField(default=5)),
                ('quote', models.TextField()),
                ('is_featured', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviews', to='catalog.product')),
            ],
            options={
                'ordering': ['sort_order', '-created_at'],
            },
        ),
    ]
