# Generated by Django 5.2.16 on 2026-08-10 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_heroslide_storesettings_about_body_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='heroslide',
            name='image',
            field=models.ImageField(max_length=500, upload_to='hero/'),
        ),
        migrations.AlterField(
            model_name='heroslide',
            name='mobile_image',
            field=models.ImageField(blank=True, max_length=500, null=True, upload_to='hero/'),
        ),
        migrations.AlterField(
            model_name='storesettings',
            name='about_image',
            field=models.ImageField(blank=True, max_length=500, null=True, upload_to='brand/'),
        ),
        migrations.AlterField(
            model_name='storesettings',
            name='craft_image',
            field=models.ImageField(blank=True, max_length=500, null=True, upload_to='brand/'),
        ),
        migrations.AlterField(
            model_name='storesettings',
            name='logo',
            field=models.ImageField(blank=True, max_length=500, null=True, upload_to='brand/'),
        ),
    ]
