# Generated by Django 5.2.16 on 2026-07-29 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='meta_description',
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AddField(
            model_name='category',
            name='meta_title',
            field=models.CharField(blank=True, max_length=70),
        ),
        migrations.AddField(
            model_name='product',
            name='care_instructions',
            field=models.TextField(blank=True, help_text='How to wash / care for this garment'),
        ),
        migrations.AddField(
            model_name='product',
            name='details_extra',
            field=models.TextField(blank=True, help_text='Any other product information shown on the PDP'),
        ),
        migrations.AddField(
            model_name='product',
            name='fit',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='product',
            name='made_in',
            field=models.CharField(blank=True, default='India', max_length=120),
        ),
        migrations.AddField(
            model_name='product',
            name='material',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='product',
            name='meta_description',
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AddField(
            model_name='product',
            name='meta_title',
            field=models.CharField(blank=True, max_length=70),
        ),
        migrations.AddField(
            model_name='product',
            name='related_products',
            field=models.ManyToManyField(blank=True, help_text="Manual 'You may also like' picks. If empty, same-category products are shown.", related_name='related_from', to='catalog.product'),
        ),
        migrations.AddField(
            model_name='product',
            name='size_chart',
            field=models.TextField(blank=True, help_text='Product-specific size chart. Leave blank to use the store default.'),
        ),
    ]
