# Generated by Django 5.2.16 on 2026-08-08 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_category_meta_description_category_meta_title_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productimage',
            options={'ordering': ['-is_primary', 'sort_order', 'id']},
        ),
        migrations.AddField(
            model_name='product',
            name='featured_image',
            field=models.ImageField(blank=True, help_text='Main image on shop cards & product page. Upload or replace here from the CMS.', null=True, upload_to='products/featured/'),
        ),
        migrations.AddField(
            model_name='productimage',
            name='is_primary',
            field=models.BooleanField(default=False, help_text='Use as main image when Featured image above is empty.'),
        ),
    ]
